eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8764


spring:
  application:
    name: service-menu

  datasource:
    url: jdbc:mysql://localhost:3306/food?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      date-format: yyyy/MM/dd
      time-zone: GMT+8p

mybatis:
  mapper-locations: classpath:mapper/*   # mapperÂ·¾¶
